-- Создание тестовых таблиц
CREATE TABLE IF NOT EXISTS "_User" (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    roles VARCHAR(255) DEFAULT 'USER'
);

CREATE TABLE IF NOT EXISTS "Shot" (
    id BIGSERIAL PRIMARY KEY,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    r DOUBLE PRECISION NOT NULL,
    in_area BOOLEAN NOT NULL,
    shot_time VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "_User"(id) ON DELETE CASCADE
);
